server:
  port: 8080
spring:
  application:
    name: "JavaHeadless"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
broadcast:
  namespace: "headless-service"
  url: "https://%s:8080/actuator/health"
  cert-chain: "/etc/istio-certs/cert-chain.pem"
  key: "/etc/istio-certs/key.pem"
  timeout: 5000
